# Generated by Django 5.2.9 on 2026-08-15 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seenmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Номер')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование заявки')),
                ('category', models.CharField(choices=[('confectionery', 'Кондитерские изделия (торты, печенье)'), ('restaurant', 'Сертификаты на рестораны и алкоголь'), ('stay', 'Сертификаты на проживание, цветы, подарки')], max_length=32, verbose_name='Категория комплимента')),
                ('category_details', models.TextField(blank=True, verbose_name='Что именно предоставляем')),
                ('company', models.CharField(max_length=500, verbose_name='Компания (получатель)')),
                ('guest_name', models.CharField(blank=True, max_length=255, verbose_name='Ф.И.О. гостя')),
                ('event_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время комплимента')),
                ('description', models.TextField(blank=True, verbose_name='Описание заявки')),
                ('initiator_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Инициатор (ID Б24)')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Подразделение инициатора')),
                ('needs_ceo', models.BooleanField(default=False, verbose_name='Согласование с ГД')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'Возвращена на доработку'), ('rejected', 'Отклонена'), ('approved', 'Согласована'), ('in_work', 'В работе у исполнителя'), ('executed', 'Исполнена'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('executor_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Исполнитель (ID Б24)')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Взята в работу')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Исполнена')),
                ('execution_comment', models.CharField(blank=True, max_length=500, verbose_name='Комментарий исполнителя')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliments', to='core.facility', verbose_name='Отель')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliments', to='core.organization', verbose_name='Юрлицо')),
            ],
            options={
                'verbose_name': 'Заявка на комплимент',
                'verbose_name_plural': 'Заявки на комплименты',
                'ordering': ['-id'],
            },
        ),
    ]
