# Generated by Django 5.2.9 on 2026-07-13 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('external_1c_id', models.CharField(blank=True, max_length=64, verbose_name='Внешний ID в 1С')),
                ('diadoc_counterparty_id', models.CharField(blank=True, max_length=64, verbose_name='ID в Диадоке')),
                ('bitrix_company_id', models.CharField(blank=True, max_length=64, verbose_name='ID компании в Битрикс24')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое название')),
                ('full_name', models.CharField(blank=True, max_length=500, verbose_name='Полное юр. название')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('external_1c_id', models.CharField(blank=True, max_length=64, verbose_name='Внешний ID в 1С')),
                ('diadoc_box_id', models.CharField(blank=True, max_length=64, verbose_name='boxId Диадока')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('category', models.CharField(choices=[('system', 'Системное'), ('process', 'Процессное')], default='process', max_length=16, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Право',
                'verbose_name_plural': 'Права',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('ops_director', models.CharField(blank=True, max_length=255, verbose_name='Операционный директор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('external_id', models.CharField(blank=True, max_length=64, verbose_name='Внешний ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Объект / отель',
                'verbose_name_plural': 'Объекты / отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.department', verbose_name='Вышестоящее подразделение')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CFO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=64, verbose_name='Код')),
                ('head', models.CharField(blank=True, max_length=255, verbose_name='Руководитель ЦФО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('external_1c_id', models.CharField(blank=True, max_length=64, verbose_name='Внешний ID в 1С/БИТ.ФИНАНС')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cfos', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'ЦФО',
                'verbose_name_plural': 'ЦФО',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('kind', models.CharField(choices=[('system', 'Системная'), ('process', 'Процессная')], default='process', max_length=16, verbose_name='Тип')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission', verbose_name='Права')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('bitrix_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID в Битрикс24')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('external_1c_id', models.CharField(blank=True, max_length=64, verbose_name='Внешний ID в 1С')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minised_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учётка Django (для входа)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.department', verbose_name='Подразделение')),
                ('facilities', models.ManyToManyField(blank=True, related_name='users', to='core.facility', verbose_name='Доступные объекты')),
                ('organizations', models.ManyToManyField(blank=True, related_name='users', to='core.organization', verbose_name='Доступные организации')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.position', verbose_name='Должность')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='core.role', verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Пользователь MiniSED',
                'verbose_name_plural': 'Пользователи MiniSED',
                'ordering': ['fio'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('bitrix24', 'Битрикс24'), ('1c', '1С'), ('diadoc', 'Диадок'), ('manual', 'Вручную'), ('other', 'Другое')], max_length=16, verbose_name='Источник')),
                ('entity_type', models.CharField(choices=[('deal', 'Сделка'), ('user', 'Пользователь'), ('company', 'Компания'), ('counterparty', 'Контрагент'), ('contract', 'Договор'), ('document', 'Документ'), ('organization', 'Организация'), ('request', 'Заявка')], max_length=32, verbose_name='Тип сущности')),
                ('external_id', models.CharField(max_length=128, verbose_name='Внешний ID')),
                ('external_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Название')),
                ('status', models.CharField(blank=True, max_length=64, verbose_name='Статус')),
                ('snapshot_json', models.JSONField(blank=True, default=dict, verbose_name='Снимок данных')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Внешняя связь',
                'verbose_name_plural': 'Внешние связи',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_extern_content_39d2f4_idx'), models.Index(fields=['source', 'entity_type', 'external_id'], name='core_extern_source_5642e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64, verbose_name='Тип события')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, max_length=32, verbose_name='Система-источник')),
                ('target_system', models.CharField(blank=True, max_length=32, verbose_name='Система-получатель')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('processing', 'В обработке'), ('done', 'Обработано'), ('error', 'Ошибка')], default='new', max_length=16, verbose_name='Статус')),
                ('payload_json', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Интеграционное событие',
                'verbose_name_plural': 'Интеграционные события',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', 'event_type'], name='core_integr_status_c67484_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_repr', models.CharField(blank=True, max_length=255, verbose_name='Кто (текст)')),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Объект (текст)')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Новое значение')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='core.userprofile', verbose_name='Кто')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
    ]
