# Generated by Django 5.2.9 on 2026-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_roles_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfo',
            name='category',
            field=models.CharField(blank=True, choices=[('sales', 'Отдел продаж'), ('revenue', 'Управление доходами'), ('marketing', 'Маркетинг'), ('booking', 'Бронирование'), ('accounting', 'Бухгалтерия'), ('hr_kdp', 'КДП'), ('hr_recruit', 'Подбор / адаптация'), ('hr_training', 'Обучение'), ('its_it', 'ИТС / ИТ'), ('sgh', 'СГХ'), ('territory', 'Содержание территории'), ('warehouse', 'Склад'), ('restaurant', 'Ресторанная служба'), ('other', 'Прочее')], max_length=32, verbose_name='Категория'),
        ),
    ]
