# Generated by Django 5.2.9 on 2026-07-26 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cfo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfo',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cfos', to='core.organization', verbose_name='Организация'),
        ),
    ]
