# Generated by Django 5.2.9 on 2026-08-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0004_alter_cfo_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeenMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_b24_id', models.IntegerField(db_index=True, verbose_name='Пользователь (ID Б24)')),
                ('object_id', models.PositiveIntegerField()),
                ('seen_at', models.DateTimeField(auto_now=True, verbose_name='Просмотрено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Отметка просмотра',
                'verbose_name_plural': 'Отметки просмотра',
                'indexes': [models.Index(fields=['user_b24_id', 'content_type'], name='core_seenma_user_b2_726bfb_idx')],
                'unique_together': {('user_b24_id', 'content_type', 'object_id')},
            },
        ),
    ]
