# Generated by Django 5.2.9 on 2026-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cfo_category_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='it_email',
            field=models.CharField(blank=True, max_length=500, verbose_name='Почта ИТ-отдела (можно несколько через запятую)'),
        ),
    ]
