# Generated by Django 5.2.9 on 2026-08-04 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_cfo_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Номер')),
                ('title', models.CharField(max_length=500, verbose_name='Название договора')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Сумма')),
                ('is_nonstandard', models.BooleanField(default=False, verbose_name='Нестандартный (не по шаблону)')),
                ('has_disagreement_protocol', models.BooleanField(default=False, verbose_name='С протоколом разногласий')),
                ('initiator_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Инициатор (ID Б24)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'Возвращён на доработку'), ('rejected', 'Отклонён'), ('approved', 'Согласован'), ('canceled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.cfo', verbose_name='ЦФО')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.organization', verbose_name='Юрлицо (ЮО)')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-id'],
            },
        ),
    ]
