# Generated by Django 5.2.9 on 2026-08-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='crm_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на CRM / сделку'),
        ),
    ]
