# Generated by Django 5.2.9 on 2026-07-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, max_length=64, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Конфиденциально')),
                ('created_by_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Создал (ID Б24)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён (soft delete)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='Номер версии')),
                ('file', models.FileField(max_length=500, upload_to='documents/%Y/%m/', verbose_name='Файл')),
                ('original_filename', models.CharField(blank=True, max_length=500, verbose_name='Оригинальное имя')),
                ('uploaded_by_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Загрузил (ID Б24)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('change_comment', models.TextField(blank=True, verbose_name='Комментарий к версии')),
                ('is_current', models.BooleanField(default=False, verbose_name='Актуальная')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер, байт')),
                ('mime_type', models.CharField(blank=True, max_length=128, verbose_name='MIME-тип')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='SHA-256')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'ordering': ['document_id', 'version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion', verbose_name='Актуальная версия'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx'),
        ),
    ]
