# Generated by Django 5.2.9 on 2026-07-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_key', models.CharField(db_index=True, max_length=128, verbose_name='Ключ редактора')),
                ('status', models.CharField(choices=[('active', 'Редактируется'), ('saving', 'Сохранение'), ('closed', 'Закрыта'), ('error', 'Ошибка')], default='active', max_length=16)),
                ('opened_by_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Открыл (ID Б24)')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_callback_status', models.IntegerField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('base_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='documents.documentversion', verbose_name='Редактируемая версия')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='documents.document')),
                ('saved_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion', verbose_name='Сохранённая версия')),
            ],
            options={
                'verbose_name': 'Сессия редактирования',
                'verbose_name_plural': 'Сессии редактирования',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['document', 'status'], name='documents_e_documen_cfd273_idx')],
            },
        ),
    ]
