# Generated by Django 5.2.9 on 2026-07-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_roles_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Номер')),
                ('request_type', models.CharField(choices=[('ecp', 'Заявка на ЭЦП'), ('mchd', 'Заявка на МЧД'), ('poa', 'Заявка на доверенность')], max_length=32, verbose_name='Тип заявки')),
                ('initiator_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Инициатор (ID Б24)')),
                ('subject_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО сотрудника')),
                ('subject_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Сотрудник (ID Б24)')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Подразделение')),
                ('basis', models.TextField(blank=True, verbose_name='Основание оформления')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'Возвращена на доработку'), ('approved', 'Согласована'), ('in_work', 'В работе'), ('issued', 'Выпущена / оформлена'), ('rejected', 'Отклонена'), ('closed', 'Закрыта')], default='draft', max_length=20, verbose_name='Статус')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Доп. поля')),
                ('external_1c_id', models.CharField(blank=True, max_length=64, verbose_name='Внешний ID в 1С')),
                ('external_diadoc_id', models.CharField(blank=True, max_length=64, verbose_name='Внешний ID Диадока')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('cfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_requests', to='core.cfo', verbose_name='ЦФО')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reg_requests', to='core.facility', verbose_name='Объект')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_requests', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Регламентная заявка',
                'verbose_name_plural': 'Регламентные заявки',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['request_type', 'status'], name='requests_re_request_039495_idx')],
            },
        ),
    ]
