# Generated by Django 5.2.9 on 2026-07-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cfo_category'),
        ('requests_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryrequest',
            name='delivery_comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий к передаче'),
        ),
        migrations.AddField(
            model_name='regulatoryrequest',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('personally', 'Лично'), ('courier', 'Курьером'), ('post', 'Почтой'), ('edo', 'ЭДО / электронно'), ('other', 'Другое')], max_length=20, verbose_name='Способ передачи'),
        ),
        migrations.AddField(
            model_name='regulatoryrequest',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Исполнена'),
        ),
        migrations.AddField(
            model_name='regulatoryrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Получено инициатором'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequest',
            name='request_type',
            field=models.CharField(choices=[('poa', 'Заявка на доверенность'), ('mchd', 'Заявка на МЧД'), ('ecp', 'Заявка на ЭЦП')], max_length=32, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'Возвращена на доработку'), ('rejected', 'Отклонена'), ('approved', 'Согласована'), ('to_legal', 'Передана юристам'), ('legal_work', 'В работе у юристов'), ('signing', 'На подписании'), ('executed', 'Исполнена'), ('closed', 'Закрыта')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(choices=[('cfo_head', 'Руководитель ЦФО'), ('sales_head', 'Руководитель отдела продаж'), ('commercial_director', 'Коммерческий директор'), ('chief_accountant', 'Главный бухгалтер УК'), ('hr_head', 'Руководитель отдела по работе с персоналом'), ('tech_director', 'Технический директор'), ('ops_director', 'Операционный директор'), ('restaurant_director', 'Директор ресторанной службы'), ('finance_director', 'Финансовый директор УК'), ('legal_dept', 'Юридический отдел'), ('final_signer', 'Финальный подписант / генеральный директор')], max_length=32, verbose_name='Роль')),
                ('user_b24_id', models.IntegerField(verbose_name='Сотрудник (ID Б24)')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('cfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.cfo', verbose_name='ЦФО')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.facility', verbose_name='Объект')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='core.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей (маршрут)',
                'indexes': [models.Index(fields=['role_code'], name='requests_re_role_co_9dda08_idx')],
            },
        ),
    ]
