# Generated by Django 5.2.9 on 2026-07-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_reg', '0002_regulatoryrequest_delivery_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('powers', models.TextField(blank=True, verbose_name='Полномочия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон доверенности',
                'verbose_name_plural': 'Шаблоны доверенностей (матрица)',
                'ordering': ['code'],
            },
        ),
    ]
