# Generated by Django 5.2.9 on 2026-09-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_reg', '0004_seed_power_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatoryrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'Возвращена на доработку'), ('rejected', 'Отклонена'), ('approved', 'Согласована'), ('to_legal', 'Передана юристам'), ('legal_work', 'В работе у юристов'), ('signing', 'На подписании'), ('to_it', 'Передана ИТ-специалисту'), ('it_work', 'В работе у ИТ-специалиста'), ('executed', 'Исполнена'), ('closed', 'Закрыта'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role_code',
            field=models.CharField(choices=[('cfo_head', 'Руководитель ЦФО'), ('sales_head', 'Руководитель отдела продаж'), ('commercial_director', 'Коммерческий директор'), ('chief_accountant', 'Главный бухгалтер УК'), ('hr_head', 'Руководитель отдела по работе с персоналом'), ('tech_director', 'Технический директор'), ('ops_director', 'Операционный директор'), ('restaurant_director', 'Директор ресторанной службы'), ('it_specialist', 'ИТ-специалист объекта'), ('finance_director', 'Финансовый директор УК'), ('legal_dept', 'Юридический отдел'), ('final_signer', 'Финальный подписант / генеральный директор'), ('ceo_assistant', 'Помощник генерального директора'), ('confectioner', 'Кондитерский цех')], max_length=32, verbose_name='Роль'),
        ),
    ]
