# Generated by Django 5.2.9 on 2026-09-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_reg', '0005_alter_regulatoryrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryrequest',
            name='executor_b24_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Исполнитель (ID Б24)'),
        ),
    ]
