# Generated by Django 5.2.9 on 2026-09-09 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_reg', '0006_regulatoryrequest_executor_b24_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatoryrequest',
            name='source_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revocations', to='requests_reg.regulatoryrequest', verbose_name='Отзываемая доверенность'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequest',
            name='request_type',
            field=models.CharField(choices=[('poa', 'Заявка на доверенность'), ('mchd', 'Заявка на МЧД'), ('ecp', 'Заявка на ЭЦП'), ('revoke', 'Заявка на отзыв доверенности/МЧД')], max_length=32, verbose_name='Тип заявки'),
        ),
    ]
