# Generated by Django 5.2.9 on 2026-09-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_reg', '0007_regulatoryrequest_source_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_by_b24_id', models.IntegerField(verbose_name='Передал (ID Б24)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('ended_by_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Вернул (ID Б24)')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Передача функций СБ юристам',
                'verbose_name_plural': 'Передача функций СБ юристам',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='regulatoryrequest',
            name='check_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к проверке'),
        ),
        migrations.AddField(
            model_name='regulatoryrequest',
            name='check_result',
            field=models.CharField(blank=True, choices=[('approved', 'Согласовано без замечаний'), ('approved_remarks', 'Согласовано с замечаниями'), ('rejected', 'Не согласовано')], max_length=20, verbose_name='Решение по проверке'),
        ),
        migrations.AddField(
            model_name='regulatoryrequest',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Взята в работу'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequest',
            name='request_type',
            field=models.CharField(choices=[('poa', 'Заявка на доверенность'), ('mchd', 'Заявка на МЧД'), ('ecp', 'Заявка на ЭЦП'), ('revoke', 'Заявка на отзыв доверенности/МЧД'), ('check', 'Заявка на проверку лица')], max_length=32, verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='regulatoryrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('on_approval', 'На согласовании'), ('returned', 'Возвращена на доработку'), ('rejected', 'Отклонена'), ('approved', 'Согласована'), ('to_legal', 'Передана юристам'), ('legal_work', 'В работе у юристов'), ('signing', 'На подписании'), ('to_it', 'Передана ИТ-специалисту'), ('it_work', 'В работе у ИТ-специалиста'), ('check_work', 'На исполнении'), ('executed', 'Исполнена'), ('closed', 'Закрыта'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role_code',
            field=models.CharField(choices=[('cfo_head', 'Руководитель ЦФО'), ('sales_head', 'Руководитель отдела продаж'), ('commercial_director', 'Коммерческий директор'), ('chief_accountant', 'Главный бухгалтер УК'), ('hr_head', 'Руководитель отдела по работе с персоналом'), ('tech_director', 'Технический директор'), ('ops_director', 'Операционный директор'), ('restaurant_director', 'Директор ресторанной службы'), ('it_specialist', 'ИТ-специалист объекта'), ('finance_director', 'Финансовый директор УК'), ('legal_dept', 'Юридический отдел'), ('final_signer', 'Финальный подписант / генеральный директор'), ('ceo_assistant', 'Помощник генерального директора'), ('confectioner', 'Кондитерский цех'), ('security_advisor', 'Советник генерального директора по безопасности')], max_length=32, verbose_name='Роль'),
        ),
    ]
