# Generated by Django 5.2.9 on 2026-07-10 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitrixPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, verbose_name='Домен портала')),
                ('member_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='member_id портала')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Портал Битрикс24',
                'verbose_name_plural': 'Порталы Битрикс24',
            },
        ),
        migrations.CreateModel(
            name='BitrixApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=128, verbose_name='REST-метод')),
                ('ok', models.BooleanField(default=False, verbose_name='Успех')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP-код')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='bitrix.bitrixportal')),
            ],
            options={
                'verbose_name': 'Лог вызова Битрикс24',
                'verbose_name_plural': 'Логи вызовов Битрикс24',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BitrixToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='access_token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='refresh_token')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('portal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='bitrix.bitrixportal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Токен Битрикс24',
                'verbose_name_plural': 'Токены Битрикс24',
            },
        ),
    ]
