# Generated by Django 5.2.9 on 2026-07-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(default='generic', max_length=64, verbose_name='Тип согласования')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Название')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('flow_type', models.CharField(choices=[('parallel', 'Параллельное'), ('sequential', 'Последовательное')], default='parallel', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'На согласовании'), ('returned', 'Возвращено на доработку'), ('completed', 'Согласовано'), ('rejected', 'Отклонено'), ('canceled', 'Отменено'), ('closed', 'Закрыто')], default='draft', max_length=20, verbose_name='Статус')),
                ('current_round', models.PositiveIntegerField(default=0, verbose_name='Текущий круг')),
                ('initiator_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Инициатор (ID Б24)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Согласование',
                'verbose_name_plural': 'Согласования (ядро)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Номер круга')),
                ('result', models.CharField(choices=[('pending', 'В процессе'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('returned', 'Возвращено на доработку')], default='pending', max_length=16, verbose_name='Итог')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='approvalflow.approval')),
            ],
            options={
                'verbose_name': 'Круг согласования',
                'verbose_name_plural': 'Круги согласования',
                'ordering': ['approval_id', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('internal', 'Сотрудник'), ('external', 'Внешний email')], max_length=10, verbose_name='Тип')),
                ('b24_user_id', models.IntegerField(blank=True, null=True, verbose_name='ID сотрудника Б24')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('role', models.CharField(blank=True, max_length=64, verbose_name='Процессная роль')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязателен')),
                ('decision', models.CharField(choices=[('waiting', 'Ожидает'), ('approved', 'Согласовано'), ('rejected', 'Отклонено')], default='waiting', max_length=16, verbose_name='Решение')),
                ('decision_comment', models.TextField(blank=True, verbose_name='Комментарий к решению')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('external_token', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Токен внешней ссылки')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='approvalflow.approvalround')),
            ],
            options={
                'verbose_name': 'Согласующий',
                'verbose_name_plural': 'Согласующие',
                'ordering': ['round_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRouteChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Кто изменил')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_route_snapshot', models.JSONField(blank=True, default=list, verbose_name='Маршрут до')),
                ('new_route_snapshot', models.JSONField(blank=True, default=list, verbose_name='Маршрут после')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Причина')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_changes', to='approvalflow.approval')),
            ],
            options={
                'verbose_name': 'Изменение маршрута',
                'verbose_name_plural': 'Изменения маршрута',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_file', models.FileField(max_length=500, upload_to='approval_sheets/%Y/%m/', verbose_name='Файл')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('xlsx', 'XLSX')], default='pdf', max_length=8, verbose_name='Формат')),
                ('generated_by_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Кто сформировал')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='approvalflow.approval')),
            ],
            options={
                'verbose_name': 'Лист согласования',
                'verbose_name_plural': 'Листы согласования',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='approval',
            index=models.Index(fields=['content_type', 'object_id'], name='approvalflo_content_481ba9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalround',
            unique_together={('approval', 'round_number')},
        ),
    ]
