# Generated by Django 5.2.9 on 2026-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvalflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalround',
            name='opening_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий инициатора при направлении'),
        ),
    ]
