# Generated by Django 5.2.9 on 2025-12-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Сумма",
                    ),
                ),
                ("author_b24_id", models.IntegerField(verbose_name="Автор (ID в Б24)")),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "crm_link",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ссылка на CRM"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В работе"),
                            ("completed", "Согласован"),
                            ("rejected", "Отклонён"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Согласование",
                "verbose_name_plural": "Согласования",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AgreementDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("file", "Файл"), ("link", "Ссылка")],
                        default="file",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="agreements/",
                        verbose_name="Файл",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Ссылка")),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="approvals.agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("internal", "Сотрудник Б24"),
                            ("external", "Внешний email"),
                        ],
                        max_length=10,
                        verbose_name="Тип участника",
                    ),
                ),
                (
                    "b24_user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID пользователя Б24"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидает"),
                            ("approved", "Согласовано"),
                            ("rejected", "Отклонено"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата решения"
                    ),
                ),
                (
                    "external_token",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="Токен внешней ссылки",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок согласования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="approvals.agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник",
                "verbose_name_plural": "Участники",
            },
        ),
    ]
