# Generated by Django 5.2.9 on 2025-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0002_decisionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("in_progress", "В работе"),
                    ("completed", "Согласован"),
                    ("rejected", "Отклонён"),
                    ("canceled", "Отменено"),
                ],
                default="in_progress",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
