# Generated by Django 5.2.9 on 2025-12-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0003_alter_agreement_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreementdocument",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="agreements/",
                verbose_name="Файл",
            ),
        ),
    ]
