# Generated by Django 4.2 on 2025-12-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0004_alter_agreementdocument_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="B24Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "b24_user_id",
                    models.IntegerField(
                        unique=True, verbose_name="ID пользователя Б24"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Корпоративный email"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Связка Б24 ↔ email",
                "verbose_name_plural": "Связки Б24 ↔ email",
            },
        ),
    ]
