# Generated by Django 5.2.9 on 2025-12-07 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0005_b24identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название шаблона"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("author_b24_id", models.IntegerField(verbose_name="Автор (ID в Б24)")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("private", "Только мне"),
                            ("public", "Всем пользователям"),
                            ("group", "Определённой группе"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="Область видимости",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
            ],
            options={
                "verbose_name": "Шаблон согласования",
                "verbose_name_plural": "Шаблоны согласований",
            },
        ),
        migrations.CreateModel(
            name="ApprovalTemplateParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("internal", "Сотрудник Б24"),
                            ("external", "Внешний email"),
                        ],
                        default="internal",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "b24_user_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID пользователя Б24"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок согласования"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Описание / инструкция для участника",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="approvals.approvaltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник шаблона",
                "verbose_name_plural": "Участники шаблона",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalTemplateAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "b24_user_id",
                    models.IntegerField(verbose_name="ID пользователя Б24"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="approvals.approvaltemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ к шаблону",
                "verbose_name_plural": "Доступы к шаблонам",
                "unique_together": {("template", "b24_user_id")},
            },
        ),
    ]
