# Generated by Django 5.2.9 on 2025-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0006_approvaltemplate_approvaltemplateparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="prev_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="prev_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("waiting", "Ожидает"),
                    ("approved", "Согласовано"),
                    ("rejected", "Отклонено"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
