# Generated by Django 5.2.9 on 2025-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0007_participant_prev_comment_participant_prev_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="flow_type",
            field=models.CharField(
                choices=[
                    ("parallel", "Параллельное"),
                    ("sequential", "Последовательное"),
                ],
                default="parallel",
                max_length=20,
                verbose_name="Тип согласования",
            ),
        ),
    ]
