# Generated by Django 5.2.9 on 2025-12-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0008_agreement_flow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="b24identity",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Корпоративный email"),
        ),
    ]
