# Generated by Django 5.2.9 on 2026-04-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0009_alter_b24identity_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='B24UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b24_user_id', models.IntegerField(verbose_name='ID пользователя Б24')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Email пользователя Б24',
                'verbose_name_plural': 'Email-адреса пользователей Б24',
                'ordering': ['b24_user_id', 'email'],
                'unique_together': {('b24_user_id', 'email')},
            },
        ),
    ]
