# Generated by Django 5.2.9 on 2026-07-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0011_populate_b24useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='current_round',
            field=models.PositiveIntegerField(default=1, verbose_name='Текущий круг'),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='round_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Круг'),
        ),
        migrations.AddField(
            model_name='participant',
            name='round_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Круг'),
        ),
    ]
