# Generated by Django 5.2.9 on 2026-08-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0012_agreement_current_round_decisionlog_round_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
