# Generated by Django 5.2.9 on 2026-08-24 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0013_agreement_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='Круг')),
                ('author_b24_id', models.IntegerField(blank=True, null=True, verbose_name='Автор (Б24)')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_notes', to='approvals.agreement')),
            ],
            options={
                'verbose_name': 'Комментарий к кругу',
                'verbose_name_plural': 'Комментарии к кругам',
                'ordering': ['round_number', 'id'],
            },
        ),
    ]
