# Generated by Django 5.2.9 on 2026-09-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0014_roundnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionlog',
            name='admin_override_by_b24_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Решил администратор (ID Б24)'),
        ),
        migrations.AddField(
            model_name='participant',
            name='admin_override_by_b24_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Решил администратор (ID Б24)'),
        ),
    ]
